### ISSUE TITLE
[TS-19] Criar style padrão

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#126]
Alguns elementos precisam ser padronizados, como tamanho de fontes, regras de cores e margem.

**Comment by Gabiras12** [comment]
@pwener i've created a file for that. So all we need to do is import styles from that file and use it. `styles/common.styles.js`

**Comment by pwener** [comment]
@Gabiras12  well played, but in task crud we have create into `src/global-styles` one style to each component type. So, you could change this with your way. you want.

**Comment by fabio1079** [comment]
https://github.com/fga-gpp-mds/2017.1-Cadernos-APP/pull/54
