### ISSUE TITLE
[US-27] Eu como usuário desejo visualizar as atividades por categoria para ver de forma filtrada o andamento do projeto

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#130]

**Comment by fabio1079** [comment]
https://github.com/fga-gpp-mds/2017.1-Cadernos-API/issues/156
@pwener oxi ?

**Comment by fabio1079** [comment]
@pwener acho que podemos fazer essa nessa sprint, segue um prototipo dela:
https://jsfiddle.net/fabio1079/tzzp75nq/

**Comment by fabio1079** [comment]
https://github.com/fga-gpp-mds/2017.1-Cadernos-APP/pull/56
