### ISSUE TITLE
[TS-16] Criar testes

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#164]
Estamos com um deficit de testes muito grande no front-end. Não é um critério de aceitação para as contribuições, mas ainda é algo importante. Todos estão responsáveis por essa tarefa, alguns em especial por que sinto que estão com menos obrigações na Sprint.

**Comment by fabio1079** [comment]
PR: https://github.com/fga-gpp-mds/2017.1-Cadernos-APP/pull/52
