### ISSUE TITLE
[TS-22] Corrigir search na API

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#166]
Atualmente a API busca por uma ocorrência exatamente como ela está, em case sensitive. O ideal non case sensitive.

**Comment by pwener** [comment]
Oda tenta corrigir isso q vou corrigir os testes do PR q estão quebrando

**Comment by fabio1079** [comment]
Agora que estamos na SP 6, virou uma TS
