### ISSUE TITLE
Loading infinito

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#181]
Fiz um build hoje a tarde e o apk está entrando na homescreen com loading infinito, build:
https://www.dropbox.com/sh/xuktkbw1azeea56/AAC3ZHGb6uKOfT-J3dIPtjgia?dl=0

**Comment by fabio1079** [comment]
Acho que isso é pq quebraram o /books na API, mas já mandaram um fix

**Comment by fabio1079** [comment]
É, não corrigiram ainda...

![ue](https://user-images.githubusercontent.com/4295523/27503924-2cd0454c-5858-11e7-8748-b3e1005114a7.png)
