### ISSUE TITLE
Envio de imagem ao criar tarefa

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#184]
Ao criar uma tarefa a imagem tem que ser confirmada, tem dois problemas com essa feature:
- O tamanho da View da imagem está pequeno, poderia ser aumentado.
- O botão de confirmar tarefa permanece o mesmo quando clicado, não muda em nada, nem dá pra saber se tá funcionando

**Comment by fabio1079** [comment]
https://github.com/fga-gpp-mds/2017.1-Cadernos-APP/pull/64
