### ISSUE TITLE
[US-20] Eu como lider desejo editar os dados do caderno para manter o contexto digital atualizado com o contexto real

### ISSUE THREAD

**Issue by fabio1079** [fga-gpp-mds/2017.1-Cadernos-API#27]

**Comment by lucashm** [comment]
Tasks:
- botão para screen de editar caderno 🆗 
- Screen para edição de caderno 🆗 
- container para edição do caderno 🆗 
- action para editar caderno (re-uso das actions de criar caderno) 🆗 
- validar o retorno da api
- atualizar o novo nome do caderno na lista de cadernos
- redirecionar o usuário para a tela do caderno
- testar actions, reducer e component do EditUser
