### ISSUE TITLE
[US-06] Eu como artista desejo adicionar uma atividade à um caderno a qual faço parte para registrar do processo criativo

### ISSUE THREAD

**Issue by fabio1079** [fga-gpp-mds/2017.1-Cadernos-API#41]

**Comment by Renatovga2602** [comment]
Tasks:

botão para screen para adicionar atividade caderno :ok:
Screen para adição de atividade :ok:
container para edição de atividade :ok:
action para adicionar atividade (re-uso das actions de criar caderno) :ok:
validar o retorno da api :ok:
redirecionar o usuário para a tela de books :ok:
testar screen :ok:
