### ISSUE TITLE
[TS-03] Estudar como testar React

### ISSUE THREAD

**Issue by fabio1079** [fga-gpp-mds/2017.1-Cadernos-API#47]

**Comment by fabio1079** [comment]
No ambiente de teste, deve ser instalado os pacotes:
* chai
* enzyme
* react-dom(para o enzyme)
* react-test-renderer(para o enzyme)
* sinon

TODO:
Para simular ações do usuário , o talvez seja necessário o pacote mocha, mas teste requer uma configuração a parte, verificar essa configuração.

**Comment by fabio1079** [comment]
TODO:
Analisar se a configuração do mocha descrita nesse texto funciona para os testes do aplicativo:
https://blog.addjam.com/testing-react-native-with-mocha-and-enzyme-6b77cd9e52a1

**Comment by fabio1079** [comment]
TODO:
Analisar se apenas com jest o simulate já funciona:
https://github.com/airbnb/enzyme/blob/master/docs/guides/jest.md

**Comment by pwener** [comment]
pode postar os resultados ai Fábão? Ou isso vai vim no tutorialzinho?

**Comment by fabio1079** [comment]
Tenho um projeto no meu PC onde eu consegui montar um ambiente certinho e testar os components. Só o Mocha que eu resolvi não usar, estava dando mais dor de cabeça do que sendo útil. No mais o Jest com os pacotes listados acima cumprem bem o seu papel.
