### ISSUE TITLE
[TS-12] Alterar o tempo de expiracao do token de 24 horas para 2 semanas

### ISSUE THREAD

**Issue by geovanne97** [fga-gpp-mds/2017.1-Cadernos-API#54]
https://github.com/fga-gpp-mds/2017.1-Cadernos-API/blob/homolog/app/lib/json_web_token.rb

**Comment by fabio1079** [comment]
@pwener , @Gabiras12 , @filiperibeiro77 No próximo domingo(14/05) temos que fazer disso uma história, pontuá-la e colocá-la em alguma sprint.

**Comment by fabio1079** [comment]
Done
