### ISSUE TITLE
[US-24] Eu como líder desejo gerenciar financeiramente um projeto, tal que seja possível manter meus gastos.

### ISSUE THREAD

**Issue by pwener** [fga-gpp-mds/2017.1-Cadernos-API#65]
Critérios de aceitação: 
- Deve ser possível manter recursos humanos, materiais e de serviços.
- Devem ser distinguíveis entre os itens acima e nomeáveis.

**Comment by fabio1079** [comment]
Isso ta com cara de épica...

**Comment by fabio1079** [comment]
Futuras releases...
